const translations = {
    "pt": {
        "navSobre": "Sobre",
        "navTrajeto": "Trajetória",
        "navHabilidades": "Habilidades",
        "navProjetos": "Projetos",
        "navContato": "Contato",

        "heroTitulo": "Futuro Engenheiro de Software<br> & Desenvolvedor Full Stack",
        "heroTexto": "Criando soluções digitais modernas, eficientes e inteligentes.<br> Transformando ideias em experiências tecnológicas reais.",
        "btnContato": "Entrar em Contato",
        "btnTrajeto": "Conhecer Trajetória",
        "scrollDown": "↓ Role para explorar",
        "parallax": "Codificando o Futuro 🚀",

        "sobreTitulo": "Sobre Mim",
        "sobreMim": "Meu nome é <strong>Gabriel Gazeta Marcelino</strong>. Sou estudante de <strong>Engenharia de Software</strong> na <strong>UNAERP</strong> — Ribeirão Preto - SP. Apaixonado por tecnologia e inovação, busco criar soluções escaláveis, funcionais e com design moderno.",
        "trajetoTitulo": "Minha Trajetória",
        "trajeto01TI": "Primeiros Passos",
        "trajeto01TE": "Iniciei em programação em 2022, explorando <strong>HTML, CSS</strong> e <strong>JavaScript</strong>.",
        "trajeto02TI": "Curso Técnico — SENAI",
        "trajeto02TE": "Fiz cursos de programação pelo SENAI sendo eles <strong>AZ-900</strong>, <strong>AI-900</strong> aprendendo o Básico de programação.",
        "trajeto03TI": "Curso Técnico — SENAI",
        "trajeto03TE": "Comecei o curso técnico do SENAI em <strong>Análise e Desenvolvimento de Sistemas</strong> — 2024–2025. Desenvolvendo lógica de programação e projetos reais. <strong><a href='#projetos' class='cursor-pointer'>Clique aqui para ir</a></strong>.",
        "trajeto04TI": "Processo Escolar",
        "trajeto04TE": "Terminando o <strong>Ensino Médio</strong> na escola <strong>SESI-227</strong> — 2025",
        "trajeto05TI": "UNAERP",
        "trajeto05TE": "Cursando <strong>Engenharia de Software</strong>, focando em <strong>Full Stack</strong> e arquitetura de sistemas — 2025 - 202#.",
        "trajeto06TI": "Expansão de Competências",
        "trajeto06TE": "Melhorando meu <strong>JavaScript</strong> e aprofundando conhecimentos.",
        "trajeto07TI": "Projetos Pessoais",
        "trajeto07TE": " Desenvolvimento de portfólio interativo, APIs em JS e projetos internos do SENAI. Experimentando sempre novas tecnologias.",
        "habilidadesTitulo": "Linguagens & Ferramentas",
        "projetosTitulo": "Projetos",
        "projeto01TI": "Portfólio Interativo",
        "projeto01TE": "Site pessoal moderno construído com <strong>HTML, CSS, JavaScript</strong> e <strong>Tailwind</strong>, contendo animações, partículas e temas dinâmicos.",
        "projeto01GI": "Ver no GitHub →",
        "projeto01NE": "Ver na Internet →",

        "projeto02TI": "Sistema de Login com Validação",
        "projeto02TE": "Sistema completo de login e registro com animações e validação de dados utilizando <strong>HTML, CSS, Tailwind</strong> e <strong>JavaScript</strong>.",
        "projeto02GI": "Ver no GitHub →",
        "projeto02NE": "Ver na Internet →",

        "projeto03TI": "Blog sobre Inteligência Artificial",
        "projeto03TE": "Blog criado para compartilhar conhecimentos sobre <strong>Inteligência Artificial</strong>, com layout limpo e responsivo.",
        "projeto03GI": "Ver no GitHub →",
        "projeto03NE": "Ver na Internet →",

        "projeto04TI": "RetroAquários — Projeto Criativo",
        "projeto04TE": "Site fictício criado para a venda de um produto imaginário, idealizado pelos educadores <strong>Marcelo Bruno Fuentes</strong> e <strong>Josiane Matiolli</strong>, com foco em design e criatividade.",
        "projeto04GI": "Ver no GitHub →",
        "projeto04NE": "Ver na Internet →",

        "projeto05TI": "Povos Originários do Brasil",
        "projeto05TE": "Projeto escolar orientado por <strong>Luciana Pignatta</strong>, apresentando a cultura e história dos povos originários do Brasil, com foco educativo e visual envolvente.",
        "projeto05GI": "Ver no GitHub →",
        "projeto05NE": "Ver na Internet →",

        "projeto06TI": "Contador de Horas Freelancer",
        "projeto06TE": "Aplicação prática desenvolvida para facilitar o cálculo de horas trabalhadas por freelancers da família, automatizando somas e reduzindo erros em pagamentos.",
        "projeto06GI": "Ver no GitHub →",
        "projeto06NE": "Ver na Internet →",
        "footerNome": "Gabriel Gazeta Marcelino",
        "footerSobre": "Desenvolvedor Web & Futuro Engenheiro de Software. Criando interfaces modernas, eficientes e visualmente cativantes.",
        "footerNavTitulo": "Navegação",
        "navInicio": "Início",
        "footerContatoTitulo": "Contato",
        "footerEmail": "Email",
        "footerInstagram": "Instagram",
        "footerGithub": "GitHub",
        "footerLinkedin": "LinkedIn",
        "footerWhatsapp": "WhatsApp",
        "footerDireitos": "Todos os direitos reservados."
    },

    "en": {
        "navSobre": "About",
        "navTrajeto": "Journey",
        "navHabilidades": "Skills",
        "navProjetos": "Projects",
        "navContato": "Contact",

        "heroTitulo": "Future Software Engineer<br> & Full Stack Developer",
        "heroTexto": "Creating modern, efficient, and intelligent digital solutions.<br> Turning ideas into real technological experiences.",
        "btnContato": "Contact Me",
        "btnTrajeto": "View Journey",
        "scrollDown": "↓ Scroll to explore",
        "parallax": "Coding the Future 🚀",

        "sobreTitulo": "About Me",
        "sobreMim": "My name is <strong>Gabriel Gazeta Marcelino</strong>. I am a <strong>Software Engineering</strong> student at <strong>UNAERP</strong> — Ribeirão Preto, SP. Passionate about technology and innovation, I aim to create scalable, functional solutions with modern design.",
        "trajetoTitulo": "My Journey",
        "trajeto01TI": "First Steps",
        "trajeto01TE": "I started programming in 2022, exploring <strong>HTML, CSS</strong>, and <strong>JavaScript</strong>.",
        "trajeto02TI": "Technical Course — SENAI",
        "trajeto02TE": "I took programming courses at SENAI, including <strong>AZ-900</strong> and <strong>AI-900</strong>, learning the basics of programming.",
        "trajeto03TI": "Technical Course — SENAI",
        "trajeto03TE": "I started the SENAI technical course in <strong>Systems Analysis and Development</strong> — 2024–2025. Developing programming logic and real projects. <strong><a href='#projetos' class='cursor-pointer'>Click here to go</a></strong>.",
        "trajeto04TI": "School Processr",
        "trajeto04TE": "Finishing <strong>High School</strong> at <strong>SESI-227</strong> — 2025",
        "trajeto05TI": "UNAERP",
        "trajeto05TE": "Pursuing <strong>Software Engineering</strong>, focusing on <strong>Full Stack</strong> and system architecture — 2025 - 202#.",
        "trajeto06TI": "Skills Expansion",
        "trajeto06TE": "Improving my <strong>JavaScript</strong> skills and deepening my knowledge.",
        "trajeto07TI": "Personal Projects",
        "trajeto07TE": "Development of an interactive portfolio, JS APIs, and internal SENAI projects. Always experimenting with new technologies.",
        "habilidadesTitulo": "Languages & Tools",
        "projetosTitulo": "Projects",
        "projeto01TI": "Interactive Portfolio",
        "projeto01TE": "Modern personal website built with <strong>HTML, CSS, JavaScript</strong> and <strong>Tailwind</strong>, featuring animations, particles, and dynamic themes.",
        "projeto01GI": "View on GitHub →",
        "projeto01NE": "View Online →",

        "projeto02TI": "Login System with Validation",
        "projeto02TE": "Complete login and registration system with animations and data validation using <strong>HTML, CSS, Tailwind</strong> and <strong>JavaScript</strong>.",
        "projeto02GI": "View on GitHub →",
        "projeto02NE": "View Online →",

        "projeto03TI": "Artificial Intelligence Blog",
        "projeto03TE": "Blog created to share knowledge about <strong>Artificial Intelligence</strong>, with a clean and responsive layout.",
        "projeto03GI": "View on GitHub →",
        "projeto03NE": "View Online →",

        "projeto04TI": "RetroAquários — Creative Project",
        "projeto04TE": "Fictional website created for the sale of an imaginary product, designed by educators <strong>Marcelo Bruno Fuentes</strong> and <strong>Josiane Matiolli</strong>, focused on design and creativity.",
        "projeto04GI": "View on GitHub →",
        "projeto04NE": "View Online →",

        "projeto05TI": "Indigenous Peoples of Brazil",
        "projeto05TE": "School project guided by <strong>Luciana Pignatta</strong>, showcasing the culture and history of Brazil’s indigenous peoples, with an educational and visually engaging approach.",
        "projeto05GI": "View on GitHub →",
        "projeto05NE": "View Online →",

        "projeto06TI": "Freelancer Hours Counter",
        "projeto06TE": "Practical application developed to simplify tracking of hours worked by family freelancers, automating sums and reducing errors in payments.",
        "projeto06GI": "View on GitHub →",
        "projeto06NE": "View Online →",
        "footerNome": "Gabriel Gazeta Marcelino",
        "footerSobre": "Web Developer & Future Software Engineer. Creating modern, efficient, and visually captivating interfaces.",
        "footerNavTitulo": "Navigation",
        "navInicio": "Home",
        "footerContatoTitulo": "Contact",
        "footerEmail": "Email",
        "footerInstagram": "Instagram",
        "footerGithub": "GitHub",
        "footerLinkedin": "LinkedIn",
        "footerWhatsapp": "WhatsApp",
        "footerDireitos": "All rights reserved."
    }
};